services:
  backend:
    build: 
      context: ./services/backend
      dockerfile: Dockerfile.prod
    container_name: pulseguard_backend_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ./services/backend/.env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - net

  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
      args:
        VITE_SERVER_URL: http://localhost:3000
    container_name: pulseguard_web_prod
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - net
      
  db:
    image: postgres:15-alpine
    container_name: onRoute_db_prod
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgdata:

networks:
  net:
    driver: bridge